/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alireza Keshavarzi
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlusManfi = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        Point_ = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        Zarb = new javax.swing.JButton();
        Menha_ = new javax.swing.JButton();
        Pl_ = new javax.swing.JButton();
        Equal_ = new javax.swing.JButton();
        AllClear_ = new javax.swing.JButton();
        outp = new javax.swing.JTextField();
        Tagsim = new javax.swing.JButton();
        Edit_ = new javax.swing.JButton();
        EM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PlusManfi.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        PlusManfi.setText("+/-");
        PlusManfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusManfiActionPerformed(evt);
            }
        });

        b0.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        Point_.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        Point_.setText(".");

        b3.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        Zarb.setBackground(new java.awt.Color(0, 255, 153));
        Zarb.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        Zarb.setText("x");
        Zarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZarbActionPerformed(evt);
            }
        });

        Menha_.setBackground(new java.awt.Color(0, 255, 153));
        Menha_.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        Menha_.setText("-");
        Menha_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menha_ActionPerformed(evt);
            }
        });

        Pl_.setBackground(new java.awt.Color(0, 255, 153));
        Pl_.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        Pl_.setText("+");
        Pl_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pl_ActionPerformed(evt);
            }
        });

        Equal_.setBackground(new java.awt.Color(51, 51, 255));
        Equal_.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        Equal_.setForeground(new java.awt.Color(255, 255, 255));
        Equal_.setText("=");
        Equal_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Equal_ActionPerformed(evt);
            }
        });

        AllClear_.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        AllClear_.setForeground(new java.awt.Color(255, 51, 51));
        AllClear_.setText("C");
        AllClear_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllClear_ActionPerformed(evt);
            }
        });

        outp.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        outp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        outp.setText(" 0");
        outp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outpActionPerformed(evt);
            }
        });

        Tagsim.setBackground(new java.awt.Color(0, 255, 153));
        Tagsim.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        Tagsim.setText("÷");
        Tagsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TagsimActionPerformed(evt);
            }
        });

        Edit_.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        Edit_.setText("Edit");
        Edit_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_ActionPerformed(evt);
            }
        });

        EM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EM.setForeground(new java.awt.Color(255, 51, 51));
        EM.setText("Message : ");
        EM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AllClear_, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(96, 96, 96)
                                    .addComponent(Edit_, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PlusManfi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Point_, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Equal_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pl_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Menha_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Zarb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tagsim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(outp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EM, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AllClear_, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Edit_, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PlusManfi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Point_, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tagsim, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Zarb, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Menha_, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pl_, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Equal_, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String s="";
    //int a[] = new int[4];
    String s1 = "";
    String s2 = "";
    
    int a=0;
    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        s += b6.getText();
        outp.setText(s);
    }//GEN-LAST:event_b6ActionPerformed

    private void Menha_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menha_ActionPerformed
        a = 2;
        s += Menha_.getText();
        outp.setText(s);
    }//GEN-LAST:event_Menha_ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        
        s += b0.getText();
        outp.setText(s);
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        s += b1.getText();
        outp.setText(s);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        s += b2.getText();
        outp.setText(s);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        s += b3.getText();
        outp.setText(s);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        s += b4.getText();
        outp.setText(s);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        s += b5.getText();
        outp.setText(s);
    }//GEN-LAST:event_b5ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        s += b7.getText();
        outp.setText(s);
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        s += b8.getText();
        outp.setText(s);
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        s += b9.getText();
        outp.setText(s);
    }//GEN-LAST:event_b9ActionPerformed

    private void outpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outpActionPerformed
        //outp.setText(b3.getText());
    }//GEN-LAST:event_outpActionPerformed

    private void AllClear_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllClear_ActionPerformed
        s = "";
        outp.setText(s);
    }//GEN-LAST:event_AllClear_ActionPerformed

    private void PlusManfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusManfiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlusManfiActionPerformed

    private void Equal_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Equal_ActionPerformed
        
        switch(a){
            case 1:
                for(int i=0 ; i<s.length(); i++){
                    if(s.charAt(i) == '+') {s1 = s.substring(0, i); s2 = s.substring(i+1, s.length()); break;}
                }
                
                int a,b;
                if (!s1.equals(null) && !s2.equals(null)){
                    if ( (s1.length() <= 8 && s2.length() <= 8) ){
                        a = Integer.parseInt(s1);
                        b = Integer.parseInt(s2);
                        a = a+b;
                        s = Integer.toString(a);
                        outp.setText(s);
                    }
                    else { EM.setText("Error : The maximum length number is 8."); s = "";}
                }
                else { EM.setText("Error : First Enter a number."); s = ""; s1 = ""; s2 = "";}
                
                
            break;
                
            case 2:
               for(int i=0 ; i<s.length(); i++){
                    if(s.charAt(i) == '-') {s1 = s.substring(0, i); s2 = s.substring(i+1, s.length()); break;}
                    
                }
               
               
               if(s1.length() <= 8 || s2.length() <= 8){
                    a = Integer.parseInt(s1);
                    b = Integer.parseInt(s2);
                    a = a-b;
                    s = Integer.toString(a);
                    outp.setText(s);
               }
               else if ( (s1.equals(null)) || (s2.equals(null)) ){ EM.setText("Error : First Enter a number."); s = ""; s1 = ""; s2 = "";}
               else {EM.setText("Error : The maximum length number is 8."); s = "";}
            break;
                
            case 3:
                for(int i=0 ; i<s.length(); i++){
                    if(s.charAt(i) == 'x') {s1 = s.substring(0, i); s2 = s.substring(i+1, s.length()); break;}
                    
                    
                }
                
                if(s1.length() <= 8 || s2.length() <= 8){
                    a = Integer.parseInt(s1);
                    b = Integer.parseInt(s2);
                    a = a*b;
                    s = Integer.toString(a);
                    outp.setText(s);
                }
                else if ( (s1.equals(null)) || (s2.equals(null)) ){ EM.setText("Error : First Enter a number."); s = ""; s1 = ""; s2 = "";}
                else {EM.setText("Error : The maximum length number is 8."); s = "";}
            break;
                
            case 4:
                for(int i=0 ; i<s.length(); i++){
                    if(s.charAt(i) == '÷') {s1 = s.substring(0, i); s2 = s.substring(i+1, s.length()); break;}
                    
                    
                }
                if(s1.length() <= 8 || s2.length() <= 8){
                    a = Integer.parseInt(s1);
                    b = Integer.parseInt(s2);
                    a = a/b;
                    s = Integer.toString(a);
                    outp.setText(s);
                }
                else if ( (s1.equals(null)) || (s2.equals(null)) ){ EM.setText("Error : First Enter a number."); s = ""; s1 = ""; s2 = "";}
                else {EM.setText("Error : The maximum length number is 8."); s = "";}
            break;
                
        }
    }//GEN-LAST:event_Equal_ActionPerformed

    private void Edit_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_ActionPerformed
        
        
    }//GEN-LAST:event_Edit_ActionPerformed

    private void Pl_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pl_ActionPerformed
        a =1;
        s += Pl_.getText();
        outp.setText(s);
    }//GEN-LAST:event_Pl_ActionPerformed

    private void ZarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZarbActionPerformed
        a =3;
        s += Zarb.getText();
        outp.setText(s);
    }//GEN-LAST:event_ZarbActionPerformed

    private void TagsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TagsimActionPerformed
        a = 4;
        s += Tagsim.getText();
        outp.setText(s);
    }//GEN-LAST:event_TagsimActionPerformed

    //private 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllClear_;
    private javax.swing.JLabel EM;
    private javax.swing.JButton Edit_;
    private javax.swing.JButton Equal_;
    private javax.swing.JButton Menha_;
    private javax.swing.JButton Pl_;
    private javax.swing.JButton PlusManfi;
    private javax.swing.JButton Point_;
    private javax.swing.JButton Tagsim;
    private javax.swing.JButton Zarb;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JTextField outp;
    // End of variables declaration//GEN-END:variables
}
